language: python

python:
    - "3.3"
    - "2.7"

install:
    - pip install -r requirements/travis.txt

script:
  - ./lint.sh
  - python -W ignore:Dialect -m unittest discover -s test -p '*_test.py'
